<?php
return
    [
        [
            'menu_name' => '概况',
            'menu_key' => 'overview',
            'menu_type' => 1,
            'icon' => 'element-Monitor',
            'api_url' => '',
            'router_path' => 'overview',
            'view_path' => 'index/overview',
            'methods' => '',
            'sort' => 100,
            'status' => 1,
            'is_show' => 0,
        ],
        [
            'menu_name' => '应用中心',
            'menu_key' => 'app_center',
            'menu_type' => 0,
            'icon' => 'iconfont-icona-shouyediannao',
            'api_url' => '',
            'router_path' => 'apply',
            'view_path' => '',
            'methods' => '',
            'sort' => 60,
            'status' => 1,
            'is_show' => 1,
            'menu_attr' => 'system',
            'children' => [
                [
                    'menu_name' => '应用管理',
                    'menu_key' => 'app_index',
                    'menu_type' => 1,
                    'icon' => 'iconfont-iconyingyongshichang',
                    'api_url' => '',
                    'router_path' => 'index',
                    'view_path' => 'index/index',
                    'methods' => '',
                    'sort' => 100,
                    'status' => 1,
                    'is_show' => 1,
                ],
                [
                    'menu_name' => '我的星标',
                    'menu_key' => 'app_star',
                    'menu_type' => 1,
                    'icon' => 'iconfont-iconwodexingbiao',
                    'api_url' => '',
                    'router_path' => 'concern',
                    'view_path' => 'index/concern',
                    'methods' => '',
                    'sort' => 100,
                    'status' => 1,
                    'is_show' => 0,
                ],
                [
                    'menu_name' => '历史查看',
                    'menu_key' => 'app_record',
                    'menu_type' => 1,
                    'icon' => 'iconfont-iconchakanlishi',
                    'api_url' => '',
                    'router_path' => 'history',
                    'view_path' => 'index/history',
                    'methods' => '',
                    'sort' => 100,
                    'status' => 1,
                    'is_show' => 0,
                ]

            ]
        ],
        [
            'menu_name' => '装修发布',
            'menu_key' => 'website',
            'menu_type' => 0,
            'icon' => 'iconfont-iconicon_huojian',
            'api_url' => '',
            'router_path' => 'website',
            'view_path' => '',
            'methods' => '',
            'sort' => 90,
            'status' => 1,
            'is_show' => 1,
            'menu_attr' => 'common',
            'children' => [
                [
                    'menu_name' => '装修管理',
                    'menu_key' => 'diy',
                    'menu_type' => 0,
                    'icon' => 'iconfont-iconzhuangxiu2',
                    'api_url' => '',
                    'router_path' => 'diy',
                    'view_path' => '',
                    'methods' => '',
                    'sort' => 99,
                    'status' => 1,
                    'is_show' => 1,
                    'children' => [
                        [
                            'menu_name' => '页面装修',
                            'menu_key' => 'diy_page_decorate',
                            'menu_type' => 1,
                            'icon' => 'element-House',
                            'api_url' => '',
                            'router_path' => 'index',
                            'view_path' => 'diy/index',
                            'methods' => '',
                            'sort' => 100,
                            'status' => 1,
                            'is_show' => 1,
                        ],
                        [
                            'menu_name' => '保存',
                            'menu_key' => 'diy_page_update',
                            'menu_type' => 2,
                            'icon' => '',
                            'api_url' => 'diy/diy',
                            'router_path' => '',
                            'view_path' => '',
                            'methods' => 'post',
                            'sort' => 95,
                            'status' => 1,
                            'is_show' => 1,
                        ],
                        [
                            'menu_name' => '微页面',
                            'menu_key' => 'diy_page_list',
                            'menu_type' => 1,
                            'icon' => 'iconfont-icondianpuzhuangxiu',
                            'api_url' => 'diy/diy',
                            'router_path' => 'list',
                            'view_path' => 'diy/list',
                            'methods' => 'get',
                            'sort' => 90,
                            'status' => 1,
                            'is_show' => 1,
                        ],
                        [
                            'menu_name' => '页面路径',
                            'menu_key' => 'diy_page_route',
                            'menu_type' => 1,
                            'icon' => 'iconfont-icondianpuzhuangxiu',
                            'api_url' => 'diy/diy',
                            'router_path' => 'route',
                            'view_path' => 'diy/route',
                            'methods' => 'get',
                            'sort' => 85,
                            'status' => 1,
                            'is_show' => 1,
                        ],
                        [
                            'menu_name' => '底部导航',
                            'menu_key' => 'diy_bottom',
                            'menu_type' => 1,
                            'icon' => 'iconfont-icondibudaohang',
                            'api_url' => 'diy/bottom',
                            'router_path' => 'tabbar',
                            'view_path' => 'diy/tabbar',
                            'methods' => 'get',
                            'sort' => 80,
                            'status' => 1,
                            'is_show' => 1,
                            'children' => [
                                [
                                    'menu_name' => '保存',
                                    'menu_key' => 'diy_tabbar_update',
                                    'menu_type' => 2,
                                    'icon' => '',
                                    'api_url' => 'diy/bottom',
                                    'router_path' => '',
                                    'view_path' => '',
                                    'methods' => 'post',
                                    'sort' => 100,
                                    'status' => 1,
                                    'is_show' => 1,
                                ],
                            ],
                        ]
                    ]
                ],
                [
                    'menu_name' => '渠道管理',
                    'menu_key' => 'channel',
                    'menu_type' => 0,
                    'icon' => 'iconfont-iconicon_huojian',
                    'api_url' => '',
                    'router_path' => 'channel',
                    'view_path' => '',
                    'methods' => '',
                    'sort' => 44,
                    'status' => 1,
                    'is_show' => 1,
                    'children' => [
                        [
                            'menu_name' => '电脑端',
                            'menu_key' => 'pc_config',
                            'menu_type' => 1,
                            'icon' => '',
                            'api_url' => '',
                            'router_path' => 'pc/config',
                            'view_path' => 'channel/pc/config',
                            'methods' => '',
                            'sort' => 100,
                            'status' => 1,
                            'is_show' => 1,
                        ],
                        [
                            'menu_name' => 'H5端',
                            'menu_key' => 'h5_config',
                            'menu_type' => 1,
                            'icon' => '',
                            'api_url' => 'channel/h5/config',
                            'router_path' => 'h5/config',
                            'view_path' => 'channel/h5/config',
                            'methods' => 'put',
                            'sort' => 90,
                            'status' => 1,
                            'is_show' => 1,
                        ],
                        [
                            'menu_name' => '微信公众号',
                            'menu_key' => 'channel_wechat',
                            'menu_type' => 1,
                            'icon' => 'iconfont-iconweixingongzhonghao1',
                            'api_url' => 'wechat/access',
                            'router_path' => 'wechat',
                            'view_path' => 'channel/wechat/access',
                            'methods' => '',
                            'sort' => 80,
                            'status' => 1,
                            'is_show' => 1,
                        ],
                        [
                            'menu_name' => '发布教程',
                            'menu_key' => 'wechat_course',
                            'menu_type' => 1,
                            'icon' => '',
                            'api_url' => 'wechat/course',
                            'router_path' => 'wechat/course',
                            'view_path' => 'channel/wechat/course',
                            'methods' => 'get',
                            'sort' => 100,
                            'status' => 1,
                            'is_show' => 0,
                        ],
                        [
                            'menu_name' => '公众号配置',
                            'menu_key' => 'wechat_config',
                            'menu_type' => 1,
                            'icon' => '',
                            'api_url' => 'wechat/config',
                            'router_path' => 'wechat/config',
                            'view_path' => 'channel/wechat/config',
                            'methods' => 'get',
                            'sort' => 90,
                            'status' => 1,
                            'is_show' => 0,
                        ],
                        [
                            'menu_name' => '自定义菜单',
                            'menu_key' => 'wechat_menu',
                            'menu_type' => 1,
                            'icon' => '',
                            'api_url' => 'wechat/menu',
                            'router_path' => 'wechat/menu',
                            'view_path' => 'channel/wechat/menu',
                            'methods' => 'get',
                            'sort' => 80,
                            'status' => 1,
                            'is_show' => 0,
                        ],
                        [
                            'menu_name' => '模板消息',
                            'menu_key' => 'wechat_template_message',
                            'menu_type' => 1,
                            'icon' => '',
                            'api_url' => 'wechat/template',
                            'router_path' => 'wechat/message',
                            'view_path' => 'channel/wechat/template',
                            'methods' => 'get',
                            'sort' => 70,
                            'status' => 1,
                            'is_show' => 0,
                        ],
                        [
                            'menu_name' => '微信小程序',
                            'menu_key' => 'weapp_access',
                            'menu_type' => 1,
                            'icon' => '',
                            'api_url' => 'weapp/access',
                            'router_path' => 'weapp',
                            'view_path' => 'channel/weapp/access',
                            'methods' => 'get',
                            'sort' => 70,
                            'status' => 1,
                            'is_show' => 1,
                        ],
                        [
                            'menu_name' => '配置教程',
                            'menu_key' => 'weapp_course',
                            'menu_type' => 1,
                            'icon' => '',
                            'api_url' => 'weapp/course',
                            'router_path' => 'weapp/course',
                            'view_path' => 'channel/weapp/course',
                            'methods' => 'get',
                            'sort' => 100,
                            'status' => 1,
                            'is_show' => 0,
                        ],
                        [
                            'menu_name' => '小程序配置',
                            'menu_key' => 'weapp_config',
                            'menu_type' => 1,
                            'icon' => '',
                            'api_url' => 'weapp/config',
                            'router_path' => 'weapp/config',
                            'view_path' => 'channel/weapp/config',
                            'methods' => 'get',
                            'sort' => 90,
                            'status' => 1,
                            'is_show' => 0,
                        ],
                        [
                            'menu_name' => '订阅消息',
                            'menu_key' => 'weapp_template_message',
                            'menu_type' => 1,
                            'icon' => '',
                            'api_url' => 'weapp/template',
                            'router_path' => 'weapp/message',
                            'view_path' => 'channel/weapp/template',
                            'methods' => 'get',
                            'sort' => 80,
                            'status' => 1,
                            'is_show' => 0,
                        ],
                        [
                            'menu_name' => '小程序发布',
                            'menu_key' => 'weapp_code',
                            'menu_type' => 1,
                            'icon' => '',
                            'api_url' => 'weapp/code',
                            'router_path' => 'weapp/code',
                            'view_path' => 'channel/weapp/code',
                            'methods' => 'get',
                            'sort' => 70,
                            'status' => 1,
                            'is_show' => 0,
                        ],
                        [
                            'menu_name' => '支付宝小程序',
                            'menu_key' => 'aliapp_weapp_access',
                            'menu_type' => 1,
                            'icon' => '',
                            'api_url' => 'aliapp/access',
                            'router_path' => 'aliapp',
                            'view_path' => 'channel/aliapp/access',
                            'methods' => 'get',
                            'sort' => 50,
                            'status' => 1,
                            'is_show' => 1,
                        ],
                        [
                            'menu_name' => '支付宝配置',
                            'menu_key' => 'aliapp_config',
                            'menu_type' => 1,
                            'icon' => '',
                            'api_url' => 'aliapp/config',
                            'router_path' => 'aliapp/config',
                            'view_path' => 'channel/aliapp/config',
                            'methods' => 'put',
                            'sort' => 90,
                            'status' => 1,
                            'is_show' => 0,
                        ],
                        [
                            'menu_name' => '配置教程',
                            'menu_key' => 'aliapp_course',
                            'menu_type' => 1,
                            'icon' => '',
                            'api_url' => 'aliapp/course',
                            'router_path' => 'aliapp/course',
                            'view_path' => 'channel/aliapp/course',
                            'methods' => 'get',
                            'sort' => 100,
                            'status' => 1,
                            'is_show' => 0,
                        ],
                    ]
                ],
                [
                    'menu_name' => '素材管理',
                    'menu_key' => 'attachment',
                    'menu_type' => 1,
                    'icon' => 'iconfont-iconsucaiguanli',
                    'api_url' => 'sys/attachment',
                    'router_path' => 'attachment',
                    'view_path' => 'tools/attachment',
                    'methods' => 'get',
                    'sort' => 97,
                    'status' => 1,
                    'is_show' => 1,
                ],
            ]
        ],
        [
            'menu_name' => '会员管理',
            'menu_key' => 'member',
            'menu_type' => 0,
            'icon' => 'iconfont-iconhuiyuan2',
            'api_url' => '',
            'router_path' => 'member',
            'view_path' => '',
            'methods' => '',
            'sort' => 70,
            'status' => 1,
            'is_show' => 1,
            'menu_attr' => 'system',
            'children' => [
                [
                    'menu_name' => '会员列表',
                    'menu_key' => 'member_list',
                    'menu_type' => 1,
                    'icon' => 'iconfont-iconhuiyuanliebiao',
                    'api_url' => 'member/member',
                    'router_path' => 'member',
                    'view_path' => 'member/member',
                    'methods' => 'get',
                    'sort' => 100,
                    'status' => 1,
                    'is_show' => 1,
                    'children' => [
                        [

                            'menu_name' => '编辑',
                            'menu_key' => 'member_update',
                            'menu_type' => 2,
                            'icon' => '',
                            'api_url' => 'member/modify/<member_id>/<field>',
                            'router_path' => '',
                            'view_path' => '',
                            'methods' => 'put',
                            'sort' => 0,
                            'status' => 1,
                            'is_show' => 1,
                        ],
                    ]
                ],
                [
                    'menu_name' => '会员详情',
                    'menu_key' => 'member_info',
                    'menu_type' => 1,
                    'icon' => '',
                    'api_url' => 'member/member/<id>',
                    'router_path' => 'detail',
                    'view_path' => 'member/member_detail',
                    'methods' => 'get',
                    'sort' => 90,
                    'status' => 1,
                    'is_show' => 0,
                ],
                [
                    'menu_name' => '会员标签',
                    'menu_key' => 'member_label',
                    'menu_type' => 1,
                    'icon' => 'iconfont-iconhuiyuanbiaoqian',
                    'api_url' => 'member/label',
                    'router_path' => 'label',
                    'view_path' => 'member/label',
                    'methods' => 'get',
                    'sort' => 80,
                    'status' => 1,
                    'is_show' => 1,
                    'children' => [
                        [

                            'menu_name' => '编辑标签',
                            'menu_key' => 'member_label_update',
                            'menu_type' => 2,
                            'icon' => '',
                            'api_url' => 'member/label/<id>',
                            'router_path' => '',
                            'view_path' => '',
                            'methods' => 'put',
                            'sort' => 0,
                            'status' => 1,
                            'is_show' => 1,
                        ],
                        [

                            'menu_name' => '添加标签',
                            'menu_key' => 'member_label_add',
                            'menu_type' => 2,
                            'icon' => '',
                            'api_url' => 'member/label',
                            'router_path' => '',
                            'view_path' => '',
                            'methods' => 'post',
                            'sort' => 0,
                            'status' => 1,
                            'is_show' => 1,
                        ],
                        [

                            'menu_name' => '删除标签',
                            'menu_key' => 'member_label_delete',
                            'menu_type' => 2,
                            'icon' => '',
                            'api_url' => 'member/label/<id>',
                            'router_path' => '',
                            'view_path' => '',
                            'methods' => 'delete',
                            'sort' => 0,
                            'status' => 1,
                            'is_show' => 1,
                        ],
                    ]
                ],
                [
                    'menu_name' => '会员积分',
                    'menu_key' => 'member_point',
                    'menu_type' => 1,
                    'icon' => 'iconfont-iconhuiyuanjifen',
                    'api_url' => 'member/account/point',
                    'router_path' => 'point',
                    'view_path' => 'member/point',
                    'methods' => 'get',
                    'sort' => 70,
                    'status' => 1,
                    'is_show' => 1,
                ],
                [
                    'menu_name' => '会员余额',
                    'menu_key' => 'member_balance',
                    'menu_type' => 1,
                    'icon' => 'iconfont-iconhuiyuanyue',
                    'api_url' => 'member/account/balance',
                    'router_path' => 'balance',
                    'view_path' => 'member/balance',
                    'methods' => 'get',
                    'sort' => 60,
                    'status' => 1,
                    'is_show' => 1,
                ],
                [
                    'menu_name' => '会员佣金',
                    'menu_key' => 'member_commission',
                    'menu_type' => 1,
                    'icon' => 'iconfont-iconhuiyuanyongjin',
                    'api_url' => 'member/account/commission',
                    'router_path' => 'commission',
                    'view_path' => 'member/commission',
                    'methods' => 'get',
                    'sort' => 50,
                    'status' => 1,
                    'is_show' => 1,
                ],
                [
                    'menu_name' => '财务流水',
                    'menu_key' => 'site_account_list',
                    'menu_type' => 1,
                    'icon' => 'iconfont-iconcaiwuliushui',
                    'api_url' => 'finance/account',
                    'router_path' => 'account',
                    'view_path' => 'finance/account',
                    'methods' => 'get',
                    'sort' => 40,
                    'status' => 1,
                    'is_show' => 1,
                ],
                [
                    'menu_name' => '线下支付',
                    'menu_key' => 'site_pay_offlinepay',
                    'menu_type' => 1,
                    'icon' => 'iconfont-iconxianxiazhifu2',
                    'api_url' => 'pay/offlinepay',
                    'router_path' => 'pay/offlinepay',
                    'view_path' => 'finance/offlinepay',
                    'methods' => 'get',
                    'sort' => 30,
                    'status' => 1,
                    'is_show' => 1,
                    'children' => [
                        [
                            'menu_name' => '通过',
                            'menu_key' => 'site_pay_audit_pass',
                            'menu_type' => 2,
                            'icon' => '',
                            'api_url' => 'pay/pass/:out_trade_no',
                            'router_path' => '',
                            'view_path' => '',
                            'methods' => 'put',
                            'sort' => 99,
                            'status' => 1,
                            'is_show' => 1,
                        ],
                        [
                            'menu_name' => '拒绝',
                            'menu_key' => 'site_pay_audit_refuse',
                            'menu_type' => 2,
                            'icon' => '',
                            'api_url' => 'pay/refuse/:out_trade_no',
                            'router_path' => '',
                            'view_path' => '',
                            'methods' => 'put',
                            'sort' => 99,
                            'status' => 1,
                            'is_show' => 1,
                        ],
                    ]
                ],
                [
                    'menu_name' => '支付单据详情',
                    'menu_key' => 'site_pay_detail',
                    'menu_type' => 1,
                    'icon' => 'element-Postcard',
                    'api_url' => 'pay/detail',
                    'router_path' => 'pay/detail',
                    'view_path' => 'finance/pay_detail',
                    'methods' => 'get',
                    'sort' => 20,
                    'status' => 1,
                    'is_show' => 0,
                ],
                [
                    'menu_name' => '会员提现',
                    'menu_key' => 'cash_out_list',
                    'menu_type' => 1,
                    'icon' => 'iconfont-iconhuiyuantixian',
                    'api_url' => 'member/cash_out',
                    'router_path' => 'cash_out',
                    'view_path' => 'finance/cash_out',
                    'methods' => 'get',
                    'sort' => 10,
                    'status' => 1,
                    'is_show' => 1,
                ],
            ],
        ],
        [
            'menu_name' => '系统设置',
            'menu_key' => 'setting',
            'menu_type' => 0,
            'icon' => 'iconfont-iconshezhi1',
            'api_url' => '',
            'router_path' => 'setting',
            'view_path' => '',
            'methods' => '',
            'sort' => 40,
            'status' => 1,
            'is_show' => 1,
            'menu_attr' => 'common',
            'children' => [
                [
                    'menu_name' => '基础设置',
                    'menu_key' => 'basis',
                    'menu_type' => 0,
                    'icon' => 'element-Setting',
                    'api_url' => '',
                    'router_path' => 'basis',
                    'view_path' => '',
                    'methods' => '',
                    'sort' => 49,
                    'status' => 1,
                    'is_show' => 1,
                    'children' => [
                        [
                            'menu_name' => '网站设置',
                            'menu_key' => 'setting_system',
                            'menu_type' => 1,
                            'icon' => 'element-Basketball',
                            'api_url' => 'sys/config/website',
                            'router_path' => 'system',
                            'view_path' => 'setting/system',
                            'methods' => 'get',
                            'sort' => 100,
                            'status' => 1,
                            'is_show' => 1,
                        ],
                        [
                            'menu_name' => '版权设置',
                            'menu_key' => 'setting_copyright',
                            'menu_type' => 1,
                            'icon' => 'iconfont-iconbanquan1',
                            'api_url' => 'sys/config/copyright',
                            'router_path' => 'copyright',
                            'view_path' => 'setting/copyright',
                            'methods' => 'get',
                            'sort' => 90,
                            'status' => 1,
                            'is_show' => 1,
                        ],
                        [
                            'menu_name' => '后台登录',
                            'menu_key' => 'setting_login',
                            'menu_type' => 1,
                            'icon' => 'iconfont-iconzhuceshezhi',
                            'api_url' => 'sys/config/login',
                            'router_path' => 'adminlogin',
                            'view_path' => 'setting/adminlogin',
                            'methods' => 'get',
                            'sort' => 80,
                            'status' => 1,
                            'is_show' => 1,
                        ],
                        [
                            'menu_name' => '会员设置',
                            'menu_key' => 'setting_member',
                            'menu_type' => 1,
                            'icon' => 'iconfont-iconjiaoseyonghu',
                            'api_url' => 'member/config/member',
                            'router_path' => 'member',
                            'view_path' => 'setting/member',
                            'methods' => 'get',
                            'sort' => 70,
                            'status' => 1,
                            'is_show' => 1,
                        ],
                        [
                            'menu_name' => '注册登录',
                            'menu_key' => 'setting_login_register',
                            'menu_type' => 1,
                            'icon' => 'iconfont-icondenglu',
                            'api_url' => 'member/config/login',
                            'router_path' => 'login',
                            'view_path' => 'setting/login',
                            'methods' => 'get',
                            'sort' => 60,
                            'status' => 1,
                            'is_show' => 1,
                        ],
                        [
                            'menu_name' => '协议管理',
                            'menu_key' => 'system_agreement',
                            'menu_type' => 1,
                            'icon' => 'element-Notebook',
                            'api_url' => 'sys/agreement',
                            'router_path' => 'agreement',
                            'view_path' => 'setting/agreement',
                            'methods' => 'get',
                            'sort' => 50,
                            'status' => 1,
                            'is_show' => 1,
                        ],
                        [
                            'menu_name' => '协议编辑',
                            'menu_key' => 'system_agreement_edit',
                            'menu_type' => 1,
                            'icon' => '',
                            'api_url' => 'sys/agreement/<key>',
                            'router_path' => 'agreement/edit',
                            'view_path' => 'setting/agreement_edit',
                            'methods' => 'put',
                            'sort' => 100,
                            'status' => 1,
                            'is_show' => 0,
                        ],
                        [
                            'menu_name' => '地图设置',
                            'menu_key' => 'map_setting',
                            'menu_type' => 1,
                            'icon' => 'element-Message',
                            'api_url' => 'sys/config/map',
                            'router_path' => 'map',
                            'view_path' => 'setting/map',
                            'methods' => 'get',
                            'sort' => 40,
                            'status' => 1,
                            'is_show' => 1,
                        ],
                        [
                            'menu_name' => '存储设置',
                            'menu_key' => 'setting_storage',
                            'menu_type' => 1,
                            'icon' => 'element-FolderChecked',
                            'api_url' => 'sys/storage',
                            'router_path' => 'storage',
                            'view_path' => 'setting/storage',
                            'methods' => 'get',
                            'sort' => 30,
                            'status' => 1,
                            'is_show' => 1,
                        ],
                    ]
                ],
                [
                    'menu_name' => '支付管理',
                    'menu_key' => 'setting_pay',
                    'menu_type' => 1,
                    'icon' => 'iconfont-iconzhifuguanli',
                    'api_url' => '',
                    'router_path' => 'pay',
                    'view_path' => '',
                    'methods' => 'get',
                    'sort' => 48,
                    'status' => 1,
                    'is_show' => 1,
                    'children' => [
                        [
                            'menu_name' => '支付设置',
                            'menu_key' => 'setting_pay_channel',
                            'menu_type' => 1,
                            'icon' => '',
                            'api_url' => 'pay/channel/lists',
                            'router_path' => 'channel',
                            'view_path' => 'setting/pay',
                            'methods' => 'get',
                            'sort' => 100,
                            'status' => 1,
                            'is_show' => 1,
                            'children' => [
                                [
                                    'menu_name' => '设置',
                                    'menu_key' => 'setting_pay_channel_set',
                                    'menu_type' => 2,
                                    'icon' => '',
                                    'api_url' => 'pay/channel/set/<channel>/<type>',
                                    'router_path' => '',
                                    'view_path' => '',
                                    'methods' => 'post',
                                    'sort' => 100,
                                    'status' => 1,
                                    'is_show' => 1,
                                ],
                            ]
                        ],
                        [
                            'menu_name' => '打款设置',
                            'menu_key' => 'setting_pay_transfer',
                            'menu_type' => 1,
                            'icon' => '',
                            'api_url' => 'pay/transfer',
                            'router_path' => 'transfer',
                            'view_path' => 'setting/transfer',
                            'methods' => 'get',
                            'sort' => 90,
                            'status' => 1,
                            'is_show' => 1,
                            'children' => [
                                [
                                    'menu_name' => '设置',
                                    'menu_key' => 'setting_pay_transfer_set',
                                    'menu_type' => 2,
                                    'icon' => '',
                                    'api_url' => 'pay/transfer',
                                    'router_path' => '',
                                    'view_path' => '',
                                    'methods' => 'post',
                                    'sort' => 90,
                                    'status' => 1,
                                    'is_show' => 1,

                                ],
                            ]
                        ],
                        [
                            'menu_name' => '提现设置',
                            'menu_key' => 'cash_out_config',
                            'menu_type' => 1,
                            'icon' => 'element-Postcard',
                            'api_url' => 'member/config/cash_out',
                            'router_path' => 'cash_out',
                            'view_path' => 'setting/cash_out',
                            'methods' => 'post',
                            'sort' => 59,
                            'status' => 1,
                            'is_show' => 1,
                        ],
                    ]
                ],
                [
                    'menu_name' => '消息管理',
                    'menu_key' => 'setting_notice',
                    'menu_type' => 1,
                    'icon' => 'iconfont-iconxiaoxiguanli',
                    'api_url' => '',
                    'router_path' => 'notice',
                    'view_path' => '',
                    'methods' => '',
                    'sort' => 47,
                    'status' => 1,
                    'is_show' => 1,
                    'children' => [
                        [
                            'menu_name' => '消息模板',
                            'menu_key' => 'setting_notice_template',
                            'menu_type' => 1,
                            'icon' => '',
                            'api_url' => 'notice/notice',
                            'router_path' => 'template',
                            'view_path' => 'setting/notice',
                            'methods' => 'get',
                            'sort' => 10,
                            'status' => 1,
                            'is_show' => 1,
                        ],
                        [
                            'menu_name' => '发送记录',
                            'menu_key' => 'setting_notice_records',
                            'menu_type' => 1,
                            'icon' => '',
                            'api_url' => 'notice/notice/log',
                            'router_path' => 'records',
                            'view_path' => 'setting/notice_records',
                            'methods' => 'get',
                            'sort' => 9,
                            'status' => 1,
                            'is_show' => 1,
                        ]
                    ]
                ],
                [
                    'menu_name' => '短信管理',
                    'menu_key' => 'sms_notice',
                    'menu_type' => 0,
                    'icon' => 'element-Message',
                    'api_url' => '',
                    'router_path' => 'sms',
                    'view_path' => '',
                    'methods' => '',
                    'sort' => 49,
                    'status' => 1,
                    'is_show' => 1,
                    'children' => [
                        [
                            'menu_name' => '短信设置',
                            'menu_key' => 'sms_setting',
                            'menu_type' => 1,
                            'icon' => '',
                            'api_url' => 'notice/sms',
                            'router_path' => 'setting',
                            'view_path' => 'setting/sms',
                            'methods' => 'get',
                            'sort' => 12,
                            'status' => 1,
                            'is_show' => 1,

                        ],
                        [
                            'menu_name' => '发送记录',
                            'menu_key' => 'sms_notice_records',
                            'menu_type' => 1,
                            'icon' => '',
                            'api_url' => 'notice/sms/log',
                            'router_path' => 'records',
                            'view_path' => 'setting/sms_records',
                            'methods' => 'get',
                            'sort' => 11,
                            'status' => 1,
                            'is_show' => 1,

                        ]
                    ]
                ],
                [
                    'menu_name' => '权限设置',
                    'menu_key' => 'auth',
                    'menu_type' => 0,
                    'icon' => 'iconfont-iconquanxianguanli',
                    'api_url' => '',
                    'router_path' => 'auth',
                    'view_path' => '',
                    'methods' => '',
                    'sort' => 43,
                    'status' => 1,
                    'is_show' => 1,
                    'children' => [
//                        [
//                            'menu_name' => '平台菜单',
//                            'menu_key' => 'auth_menu',
//                            'menu_type' => 1,
//                            'icon' => '',
//                            'api_url' => 'sys/menu',
//                            'router_path' => 'admin',
//                            'view_path' => 'auth/menu',
//                            'methods' => 'get',
//                            'sort' => 100,
//                            'status' => 1,
//                            'is_show' => 1,
//                            'children' => [
//                                [
//                                    'menu_name' => '新增',
//                                    'menu_key' => 'auth_menu_add',
//                                    'menu_type' => 2,
//                                    'icon' => '',
//                                    'api_url' => 'sys/menu',
//                                    'router_path' => '',
//                                    'view_path' => '',
//                                    'methods' => 'post',
//                                    'sort' => 1,
//                                    'status' => 1,
//                                    'is_show' => 1,
//                                ],
//                                [
//                                    'menu_name' => '编辑',
//                                    'menu_key' => 'auth_menu_update',
//                                    'menu_type' => 2,
//                                    'icon' => '',
//                                    'api_url' => 'sys/menu/<menu_key>',
//                                    'router_path' => '',
//                                    'view_path' => '',
//                                    'methods' => 'put',
//                                    'sort' => 1,
//                                    'status' => 1,
//                                    'is_show' => 1,
//                                ],
//                                [
//                                    'menu_name' => '删除',
//                                    'menu_key' => 'auth_menu_del',
//                                    'menu_type' => 2,
//                                    'icon' => '',
//                                    'api_url' => 'sys/menu',
//                                    'router_path' => '',
//                                    'view_path' => '',
//                                    'methods' => 'delete',
//                                    'sort' => 1,
//                                    'status' => 1,
//                                    'is_show' => 1,
//                                ],
//                                [
//                                    'menu_name' => '详情',
//                                    'menu_key' => 'auth_menu_info',
//                                    'menu_type' => 2,
//                                    'icon' => '',
//                                    'api_url' => 'sys/menu/<menu_key>',
//                                    'router_path' => '',
//                                    'view_path' => '',
//                                    'methods' => 'get',
//                                    'sort' => 0,
//                                    'status' => 1,
//                                    'is_show' => 1,
//                                ],
//                            ],
//                        ],
                        [

                            'menu_name' => '管理员',
                            'menu_key' => 'auth_user',
                            'menu_type' => 1,
                            'icon' => 'iconfont-iconyonghu',
                            'api_url' => 'user',
                            'router_path' => 'user',
                            'view_path' => 'auth/user',
                            'methods' => 'get',
                            'sort' => 80,
                            'status' => 1,
                            'is_show' => 1,
                            'children' => [
                                [
                                    'menu_name' => '新增',
                                    'menu_key' => 'auth_user_add',
                                    'menu_type' => 2,
                                    'icon' => '',
                                    'api_url' => 'user',
                                    'router_path' => '',
                                    'view_path' => '',
                                    'methods' => 'post',
                                    'sort' => 1,
                                    'status' => 1,
                                    'is_show' => 1,
                                ],
                                [
                                    'menu_name' => '编辑',
                                    'menu_key' => 'auth_user_update',
                                    'menu_type' => 2,
                                    'icon' => '',
                                    'api_url' => 'user/<uid>',
                                    'router_path' => '',
                                    'view_path' => '',
                                    'methods' => 'put',
                                    'sort' => 1,
                                    'status' => 1,
                                    'is_show' => 1,
                                ],
                                [
                                    'menu_name' => '删除',
                                    'menu_key' => 'auth_user_del',
                                    'menu_type' => 2,
                                    'icon' => '',
                                    'api_url' => 'user/<uid>',
                                    'router_path' => '',
                                    'view_path' => '',
                                    'methods' => 'delete',
                                    'sort' => 1,
                                    'status' => 1,
                                    'is_show' => 1,
                                ],
                                [
                                    'menu_name' => '详情',
                                    'menu_key' => 'auth_user_info',
                                    'menu_type' => 2,
                                    'icon' => '',
                                    'api_url' => 'user/<uid>',
                                    'router_path' => '',
                                    'view_path' => '',
                                    'methods' => 'get',
                                    'sort' => 0,
                                    'status' => 1,
                                    'is_show' => 1,
                                ],
                            ],
                        ],
                        [
                            'menu_name' => '角色管理',
                            'menu_key' => 'auth_role',
                            'menu_type' => 1,
                            'icon' => 'iconfont-iconhuiyuanliebiao',
                            'api_url' => 'sys/role',
                            'router_path' => 'role',
                            'view_path' => 'auth/role',
                            'methods' => 'get',
                            'sort' => 70,
                            'status' => 1,
                            'is_show' => 1,
                            'children' => [
                                [
                                    'menu_name' => '新增',
                                    'menu_key' => 'auth_role_add',
                                    'menu_type' => 2,
                                    'icon' => '',
                                    'api_url' => 'sys/role',
                                    'router_path' => '',
                                    'view_path' => '',
                                    'methods' => 'post',
                                    'sort' => 1,
                                    'status' => 1,
                                    'is_show' => 1,
                                ],
                                [
                                    'menu_name' => '编辑',
                                    'menu_key' => 'auth_role_update',
                                    'menu_type' => 2,
                                    'icon' => '',
                                    'api_url' => 'sys/role/<role_id>',
                                    'router_path' => '',
                                    'view_path' => '',
                                    'methods' => 'put',
                                    'sort' => 1,
                                    'status' => 1,
                                    'is_show' => 1,
                                ],
                                [
                                    'menu_name' => '删除',
                                    'menu_key' => 'auth_role_del',
                                    'menu_type' => 2,
                                    'icon' => '',
                                    'api_url' => 'sys/role/<role_id>',
                                    'router_path' => '',
                                    'view_path' => '',
                                    'methods' => 'delete',
                                    'sort' => 1,
                                    'status' => 1,
                                    'is_show' => 1,
                                ],
                            ]
                        ],
                        [
                            'menu_name' => '操作日志',
                            'menu_key' => 'auth_log',
                            'menu_type' => 1,
                            'icon' => 'element-Document',
                            'api_url' => 'sys/log',
                            'router_path' => 'log',
                            'view_path' => 'auth/log',
                            'methods' => 'get',
                            'sort' => 60,
                            'status' => 1,
                            'is_show' => 1,
                        ],
                        [
                            'menu_name' => '角色添加/编辑',
                            'menu_key' => 'role_edit',
                            'menu_type' => 1,
                            'icon' => '',
                            'api_url' => 'sys/role',
                            'router_path' => 'role_edit',
                            'view_path' => 'auth/role_edit',
                            'methods' => 'post',
                            'sort' => 60,
                            'status' => 1,
                            'is_show' => 0,
                        ],
                    ]
                ],
            ]
        ],
        [
            'menu_name' => '页面装修',
            'menu_key' => 'decorate',
            'menu_type' => 0,
            'icon' => '',
            'api_url' => '',
            'router_path' => 'decorate',
            'view_path' => '',
            'methods' => '',
            'sort' => 21,
            'status' => 1,
            'is_show' => 0,
            'children' => [
                [
                    'menu_name' => '装修',
                    'menu_key' => 'page_decorate',
                    'menu_type' => 1,
                    'icon' => '',
                    'api_url' => 'diy/diy/<id>',
                    'router_path' => 'edit',
                    'view_path' => 'diy/edit',
                    'methods' => 'put',
                    'sort' => 0,
                    'status' => 1,
                    'is_show' => 0,
                ],
                [
                    'menu_name' => '页面预览',
                    'menu_key' => 'page_preview',
                    'menu_type' => 1,
                    'icon' => '',
                    'api_url' => '',
                    'router_path' => 'preview',
                    'view_path' => 'diy/preview',
                    'methods' => '',
                    'sort' => 1,
                    'status' => 1,
                    'is_show' => 0,
                ]
            ]
        ],
        [
            'menu_name' => '应用市场',
            'menu_key' => 'app',
            'menu_type' => 0,
            'icon' => 'iconfont-iconyunshichang',
            'api_url' => '',
            'router_path' => 'app',
            'view_path' => '',
            'methods' => '',
            'sort' => 10,
            'status' => 1,
            'is_show' => 1,
            'menu_attr' => 'common',
            'children' => [
                [
                    'menu_name' => '应用插件',
                    'menu_key' => 'app_store',
                    'menu_type' => 1,
                    'icon' => 'iconfont-iconyingyongshichang11',
                    'api_url' => 'addon/local',
                    'router_path' => 'app_store',
                    'view_path' => 'app/store',
                    'methods' => 'get',
                    'sort' => 99,
                    'status' => 1,
                    'is_show' => 1,
                ],
                [
                    'menu_name' => '授权信息',
                    'menu_key' => 'app_auth',
                    'menu_type' => 1,
                    'icon' => 'iconfont-iconshouquanxinxi2',
                    'api_url' => 'niucloud/authinfo',
                    'router_path' => 'authorize',
                    'view_path' => 'app/authorize',
                    'methods' => 'get',
                    'sort' => 88,
                    'status' => 1,
                    'is_show' => 1,
                ],
                [
                    'menu_name' => '官方市场',
                    'menu_key' => 'official_market',
                    'menu_type' => 1,
                    'icon' => 'iconfont-iconguanfangshichang',
                    'api_url' => '',
                    'router_path' => 'market',
                    'view_path' => 'app/market',
                    'methods' => 'get',
                    'sort' => 77,
                    'status' => 1,
                    'is_show' => 1,
                ]
            ]
        ],
        [
            'menu_name' => '开发工具',
            'menu_key' => 'tool',
            'menu_type' => 0,
            'icon' => 'iconfont-iconcode',
            'api_url' => '',
            'router_path' => 'tools',
            'view_path' => '',
            'methods' => '',
            'sort' => 10,
            'status' => 1,
            'is_show' => 1,
            'menu_attr' => 'common',
            'children' => [
                [
                    'menu_name' => '插件开发',
                    'menu_key' => 'addon_develop',
                    'menu_type' => 1,
                    'icon' => 'iconfont-iconchajiankaifa',
                    'api_url' => '',
                    'router_path' => 'addon',
                    'view_path' => 'tools/addon/index',
                    'methods' => '',
                    'sort' => 110,
                    'status' => 1,
                    'is_show' => 1,
                ],
                [
                    'menu_name' => '插件添加/编辑',
                    'menu_key' => 'addon_edit',
                    'menu_type' => 1,
                    'icon' => '',
                    'api_url' => '',
                    'router_path' => 'addon_edit',
                    'view_path' => 'tools/addon/edit',
                    'methods' => 'get',
                    'sort' => 90,
                    'status' => 1,
                    'is_show' => 0,
                ],
                [
                    'menu_name' => '代码生成',
                    'menu_key' => 'code',
                    'menu_type' => 1,
                    'icon' => 'iconfont-icondaimashengcheng',
                    'api_url' => 'generator/generator',
                    'router_path' => 'code',
                    'view_path' => 'tools/code/index',
                    'methods' => 'get',
                    'sort' => 100,
                    'status' => 1,
                    'is_show' => 1,
                ],
                [
                    'menu_name' => '数据字典',
                    'menu_key' => 'sys_dict_dict_dict_list',
                    'menu_type' => 1,
                    'icon' => 'iconfont-iconwenzhangguanli1',
                    'api_url' => 'dict/post/post',
                    'router_path' => 'list',
                    'view_path' => 'dict/list',
                    'methods' => 'get',
                    'sort' => 90,
                    'status' => 1,
                    'is_show' => 1,
                    'children' => [
                        [
                            'menu_name' => '数据字典添加',
                            'menu_key' => 'sys_dict_dict_dict_add',
                            'menu_type' => 2,
                            'icon' => '',
                            'api_url' => 'dict',
                            'router_path' => 'edit',
                            'view_path' => 'dict/edit',
                            'methods' => 'post',
                            'sort' => 4,
                            'status' => 1,
                            'is_show' => 1,
                        ],
                        [
                            'menu_name' => '编辑',
                            'menu_key' => 'sys_dict_dict_dict_edit',
                            'menu_type' => 2,
                            'icon' => '',
                            'api_url' => 'dict/<id>',
                            'router_path' => 'edit',
                            'view_path' => 'dict/edit',
                            'methods' => 'put',
                            'sort' => 3,
                            'status' => 1,
                            'is_show' => 1,
                        ],
                        [
                            'menu_name' => '删除',
                            'menu_key' => 'sys_dict_dict_dict_delete',
                            'menu_type' => 2,
                            'icon' => '',
                            'api_url' => 'dict/<id>',
                            'router_path' => '',
                            'view_path' => '',
                            'methods' => 'delete',
                            'sort' => 2,
                            'status' => 1,
                            'is_show' => 1,
                        ],
                    ]
                ],
                [
                    'menu_name' => '生成设置',
                    'menu_key' => 'code_edit',
                    'menu_type' => 1,
                    'icon' => '',
                    'api_url' => '',
                    'router_path' => 'code/edit',
                    'view_path' => 'tools/code/edit',
                    'methods' => '',
                    'sort' => 80,
                    'status' => 1,
                    'is_show' => 0,
                ],
                [
                    'menu_name' => '更新缓存',
                    'menu_key' => 'tools_Update_cache',
                    'menu_type' => 1,
                    'icon' => 'iconfont-icongengxinhuancun1',
                    'api_url' => '',
                    'router_path' => 'update',
                    'view_path' => 'tools/updatecache',
                    'methods' => '',
                    'sort' => 60,
                    'status' => 1,
                    'is_show' => 1,
                ],
                [
                    'menu_name' => '环境检测',
                    'menu_key' => 'tools_check_environment',
                    'menu_type' => 1,
                    'icon' => 'iconfont-iconhuanjingjiance',
                    'api_url' => '',
                    'router_path' => 'detection',
                    'view_path' => 'tools/detection',
                    'methods' => '',
                    'sort' => 50,
                    'status' => 1,
                    'is_show' => 1,
                ],
                [
                    'menu_name' => '计划任务',
                    'menu_key' => 'tools_schedule',
                    'menu_type' => 1,
                    'icon' => 'iconfont-iconjihuarenwu',
                    'api_url' => 'sys/schedule/list',
                    'router_path' => 'schedule',
                    'view_path' => 'tools/schedule',
                    'methods' => '',
                    'sort' => 40,
                    'status' => 1,
                    'is_show' => 1,
                    'children' => [
                        [
                            'menu_name' => '新增',
                            'menu_key' => 'schedule_add',
                            'menu_type' => 2,
                            'icon' => '',
                            'api_url' => 'sys/schedule',
                            'router_path' => '',
                            'view_path' => '',
                            'methods' => 'post',
                            'sort' => 4,
                            'status' => 1,
                            'is_show' => 1,
                        ],
                        [
                            'menu_name' => '编辑',
                            'menu_key' => 'schedule_update',
                            'menu_type' => 2,
                            'icon' => '',
                            'api_url' => 'sys/schedule/<id>',
                            'router_path' => '',
                            'view_path' => '',
                            'methods' => 'put',
                            'sort' => 3,
                            'status' => 1,
                            'is_show' => 1,
                        ],
                        [
                            'menu_name' => '设置状态',
                            'menu_key' => 'schedule_set_status',
                            'menu_type' => 2,
                            'icon' => '',
                            'api_url' => 'schedule/modify/status/<id>',
                            'router_path' => '',
                            'view_path' => '',
                            'methods' => 'put',
                            'sort' => 2,
                            'status' => 1,
                            'is_show' => 1,
                        ],
                        [
                            'menu_name' => '删除',
                            'menu_key' => 'schedule_del',
                            'menu_type' => 2,
                            'icon' => '',
                            'api_url' => 'sys/schedule/<id>',
                            'router_path' => '',
                            'view_path' => '',
                            'methods' => 'delete',
                            'sort' => 1,
                            'status' => 1,
                            'is_show' => 1,
                        ],
                    ]
                ],
                [
                    'menu_name' => '菜单管理',
                    'menu_key' => 'auth_menu',
                    'menu_type' => 1,
                    'icon' => 'iconfont-iconcaidan',
                    'api_url' => 'sys/menu',
                    'router_path' => 'admin',
                    'view_path' => 'auth/menu',
                    'methods' => 'get',
                    'sort' => 30,
                    'status' => 1,
                    'is_show' => 1,
                    'children' => [
                        [
                            'menu_name' => '新增',
                            'menu_key' => 'auth_menu_add',
                            'menu_type' => 2,
                            'icon' => '',
                            'api_url' => 'sys/menu',
                            'router_path' => '',
                            'view_path' => '',
                            'methods' => 'post',
                            'sort' => 1,
                            'status' => 1,
                            'is_show' => 1,
                        ],
                        [
                            'menu_name' => '编辑',
                            'menu_key' => 'auth_menu_update',
                            'menu_type' => 2,
                            'icon' => '',
                            'api_url' => 'sys/menu/<menu_key>',
                            'router_path' => '',
                            'view_path' => '',
                            'methods' => 'put',
                            'sort' => 1,
                            'status' => 1,
                            'is_show' => 1,
                        ],
                        [
                            'menu_name' => '删除',
                            'menu_key' => 'auth_menu_del',
                            'menu_type' => 2,
                            'icon' => '',
                            'api_url' => 'sys/menu',
                            'router_path' => '',
                            'view_path' => '',
                            'methods' => 'delete',
                            'sort' => 1,
                            'status' => 1,
                            'is_show' => 1,
                        ],
                        [
                            'menu_name' => '详情',
                            'menu_key' => 'auth_menu_info',
                            'menu_type' => 2,
                            'icon' => '',
                            'api_url' => 'sys/menu/<menu_key>',
                            'router_path' => '',
                            'view_path' => '',
                            'methods' => 'get',
                            'sort' => 0,
                            'status' => 1,
                            'is_show' => 1,
                        ],
                    ],
                ]
            ]
        ]
    ];


